# Generated by Django 5.1.3 on 2024-11-27 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Location', models.TextField(blank=True, null=True)),
                ('Funding_agency', models.TextField(blank=True, null=True)),
                ('contracting_authority_text', models.CharField(blank=True, max_length=255, null=True)),
                ('contracting_authority_link', models.URLField(blank=True, null=True)),
                ('contracting_authority_type', models.TextField(blank=True, null=True)),
                ('Status', models.TextField(blank=True, null=True)),
                ('Budget', models.TextField(blank=True, null=True)),
                ('Award_ceiling', models.TextField(blank=True, null=True)),
                ('Award_floor', models.TextField(blank=True, null=True)),
                ('Sector', models.TextField(blank=True, null=True)),
                ('Languages', models.TextField(blank=True, null=True)),
                ('Eligible_applicants', models.TextField(blank=True, null=True)),
                ('Eligible_citizenship', models.TextField(blank=True, null=True)),
                ('Dateposted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='auction.auction')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
