# Generated by Django 5.1.3 on 2024-11-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
