# Generated by Django 5.1.3 on 2024-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='description',
        ),
        migrations.AddField(
            model_name='auction',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
