# Generated by Django 5.1.3 on 2024-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_auction_description_auction_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_details',
            old_name='type',
            new_name='contracting_authority_type',
        ),
        migrations.RemoveField(
            model_name='auction_details',
            name='Contracting_authority',
        ),
        migrations.AddField(
            model_name='auction_details',
            name='contracting_authority_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction_details',
            name='contracting_authority_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
